[versions]
agp = "8.13.2"
kotlin = "2.3.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.4"
composeBom = "2026.02.00"
androidx-material = "1.7.8"
navigationCompose = "2.9.7"
hilt_ver = "2.57.1"
jetbrainsKotlinJvm = "2.3.10"
appcompat = "1.7.1"
material = "1.13.0"
room_version = "2.8.4"
ksp_ver= "2.1.21-2.0.1"
serial_ver = "2.3.10"
ver_serial_json="1.10.0"
compose_material_ver = "1.10.3"
compose_wear = "1.5.6"
material3_exp_ver = "1.4.0"


hiltnavigation_ver ="1.3.0"
roomplagin_version = "2.8.4"
kotlinandroid_ver = "2.3.10"
kotlinx_datetime_ver = "0.7.1"
identityJvm = "202411.1"
[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 ={group = "androidx.compose.material3",name  = "material3", version.ref = "material3_exp_ver"}
androidx-compose-material ={group = "androidx.compose.material",name  = "material", version.ref = "compose_material_ver"}

androidx-material = { group = "androidx.compose.material", name = "material-icons-core" ,  version.ref = "androidx-material"}


androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
hilt = { module = "com.google.dagger:hilt-android", name = "hilt", version.ref = "hilt_ver" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", name = "hilt-compiler", version.ref = "hilt_ver" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
room-runtime = {group = "androidx.room", name ="room-runtime",version.ref="room_version"}
room = {module ="androidx.room:room-compiler" , name= "room", version.ref="room_version"}
compose-wear-material = {module ="androidx.wear.compose:compose-material", name = "compose-material", version.ref = "compose_wear" }
hilt-navigation-compose= {module ="androidx.hilt:hilt-navigation-compose", name = "hilt-navigation-compose", version.ref="hiltnavigation_ver"}
kotlinx-datetime={module = "org.jetbrains.kotlinx:kotlinx-datetime",name = "kotlinx-datetime", version.ref= "kotlinx_datetime_ver"}
identity-jvm = { group = "com.android.identity", name = "identity-jvm", version.ref = "identityJvm" }
serialisation = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "ver_serial_json" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinandroid_ver" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt_ver" }
roomplagin = {id ="androidx.room", version.ref = "roomplagin_version"}
serialzation = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serial_ver" }


ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_ver" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
android-library = { id = "com.android.library", version.ref = "agp" }

